version: "2"
services:
  web:
    build: .
    ports:
      - "5001:5000"
    volumes:
      - ./:/counter_app
    links:
      - db:mongodb
    container_name: app_web_1
    depends_on:
      - db
    stdin_open: true
    tty: true
    environment:
      FLASK_APP: manage.py
      FLASK_ENV: development
      SECRET_KEY: "you-will-never-guess"
      MONGODB_HOST: mongodb
      MONGODB_DB: app
  db:
    image: arm64v8/mongo:4.0
    platform: linux/arm64/v8
    container_name: app_db_1
    ports:
      - "27017:27017"
